"""'note'

Revision ID: 25e0c068aadc
Revises: cf3a59eff9f2
Create Date: 2018-04-25 22:50:07.735402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25e0c068aadc'
down_revision = 'cf3a59eff9f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_title', sa.String(length=50), nullable=True),
    sa.Column('note_content', sa.Text(), nullable=True),
    sa.Column('classify_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classify_id'], ['classifies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notes')
    # ### end Alembic commands ###
