"""initial migration

Revision ID: 383a4aac4377
Revises: 
Create Date: 2018-04-23 16:15:51.522953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '383a4aac4377'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'test')
    # ### end Alembic commands ###
