"""initial migration

Revision ID: 83af13e5d72f
Revises: 93499d0ebdbb
Create Date: 2018-04-23 16:16:45.201023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83af13e5d72f'
down_revision = '93499d0ebdbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'test2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test2', sa.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
