"""initial migration

Revision ID: af42f7ec14d2
Revises: 385ed2cbab25
Create Date: 2018-04-23 16:20:30.221894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af42f7ec14d2'
down_revision = '385ed2cbab25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'test')
    op.drop_column('users', 'test2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test2', sa.VARCHAR(length=20), nullable=True))
    op.add_column('users', sa.Column('test', sa.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
